#Week2 事前課題
##課題３行列積のスクラッチ
###【問題１】行列積の手計算
3x3行列Aと同じく3x3行列Bの積ABを計算する


$$
\boldsymbol{A} =
 \left[\begin{array}{c}
            -1 & 2 & 3 \\
             4 & -5 & 6 \\
             7 & 8 & -9
        \end{array}\right] \quad  \
\boldsymbol{B} = 
 \left[\begin{array}{c}
            0 & 2 & 1 \\
            0 & 2 & -8 \\
            2 & 9 & -1
            \end{array}\right] \quad
$$
$$
\begin{align} \\
\boldsymbol{A}\boldsymbol{B_{11}} &= ( -1 \cdot 0 )+( 2 \cdot 0 )+( 3 \cdot 2 )\\
\boldsymbol{A}\boldsymbol{B_{12}} &=  (-1 \cdot 2 )+( 2 \cdot 2 )+( 3 \cdot 9 )\\
\boldsymbol{A}\boldsymbol{B_{13}} &= ( -1 \cdot 1 )+( 2 \cdot -8 )+( 3 \cdot -1) \\
\boldsymbol{A}\boldsymbol{B_{21}} &=  (4 \cdot 0 )+( - 5 \cdot 0 )+( 6 \cdot 2 )\\
\boldsymbol{A}\boldsymbol{B_{22}} &=  (4 \cdot 2 )+( - 5 \cdot 2 )+( 6 \cdot 9 )\\
\boldsymbol{A}\boldsymbol{B_{23}} &=  (4 \cdot 1 )+( - 5 \cdot -8 )+( 6 \cdot -1 )\\
\boldsymbol{A}\boldsymbol{B_{31}} &=  (7 \cdot 0 )+( 8 \cdot 0 )+( -9 \cdot 2 )\\
\boldsymbol{A}\boldsymbol{B_{32}} &=  (7 \cdot 2 )+( 8 \cdot 2 )+( -9 \cdot 9 )\\
\boldsymbol{A}\boldsymbol{B_{33}} &=  (7 \cdot 1 )+( 8 \cdot -8 )+( -9 \cdot -1 )\\
\end{align} \\
\boldsymbol{A}\boldsymbol{B} =  \left[\begin{array}{c}
            6 & 29 & -20 \\
            12 & 52 & 38 \\
            -18 & -51 & -48 \\
        \end{array}\right] \quad  \
$$

＃なお、ABとBAは結果が異なるので注意

###【問題２】NumPyの関数による計算

In [3]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

print(np.dot(a_ndarray, b_ndarray))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [4]:
#行列積BAの場合
print(np.dot(b_ndarray, a_ndarray))

[[ 15  -2   3]
 [-48 -74  84]
 [ 27 -49  69]]


###【問題３】ある要素の計算を実装

In [7]:

val11 = 0
for i in range(3):
  val11 +=  a_ndarray[0, i] * b_ndarray[i, 0]

print(val11)

6


###【問題４】行列積を行う関数の作成

In [13]:
def dot_matrix_2dim(raw, col):
  dimension2_product = np.array([]) #格納配列
  
  for i in range(3):
    for k in range(3):
      val1 = 0 #初期化
      for j in range(3):
        val1 += raw[i, j] * col[j, k]
      dimension2_product = np.append(dimension2_product, val1)
  
  dimension2_product = dimension2_product.reshape(3, 3)

  return dimension2_product

print(dot_matrix_2dim(a_ndarray, b_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


###【問題５】行列積関数の一般化

In [28]:
def dot_matrix_2dim(raw, col):
  dimension2_product = np.array([]) #格納配列
  err_mess = "sucsess"

  if raw.shape[1] != col.shape[0]: #判定
    err_mess = "列数と行数が一致しません"
    return print(err_mess)
    
  else:  
    for i in range(raw.shape[0]):
      for k in range(col.shape[1]):
        val1 = 0 #初期化
        for j in range(raw.shape[1]):
          val1 += raw[i, j] * col[j, k]
        dimension2_product = np.append(dimension2_product, val1)
    dimension2_product = dimension2_product.reshape(raw.shape[0], col.shape[1])
    return dimension2_product

print(dot_matrix_2dim(a_ndarray, b_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


In [29]:

#テスト
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

dot_matrix_2dim(d_ndarray , e_ndarray)


列数と行数が一致しません


【問題６】転置

In [30]:
dot_matrix_2dim(d_ndarray , e_ndarray.T)

array([[ 46.,  -4.],
       [-34.,  73.]])