# Week3 事前課題３
## オブジェクト指向の活用
### 【問題1】これまで利用してきたクラスの列挙
---
- Pandas
  - DataFrameクラス
  - Seriesクラス
- matplotlib
  - Figureクラス
  - Axesクラス
- scikit-learn
  - LinearRegressionクラス
  
### 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙
---
- Python
  - strクラス
    - str()、capitalize()、upper()、replace()
- Pandas
  - concat()、value_counts()
  - df.カラム名 ：特定の列を抜き出すとき、カラム名がインスタンス変数として用意されている
  - loc、ilocもインスタンス変数
- scikit-learn
  - train_test_split()、fit()
  - LinearRegressionクラス
    - coef_ ：説明変数の係数
    - intercept_ ：切片


### 【問題3】標準化クラスをスクラッチで作成
---

In [9]:
class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """

    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            学習データ
        """
        self.mean_ = np.array([])
        self.var_ = np.array([])
        self.std_ = np.array([])
        cols = X.shape[1]  #列数の取得
        raws = X.shape[0]  #行数の取得

        for i in range(cols):
            self.mean_ = np.append(self.mean_, X[:, i].sum() / X[:, i].shape)
        
        for i in range(cols):
            var = 0
            for j in range(raws):
                var += (X[j, i] - self.mean_[i])**2
            self.var_ = np.append(self.var_, var / raws)
            self.std_ = np.append(self.std_, np.sqrt(var / raws))

        pass

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        cols = X.shape[1]  #列数の取得
        raws = X.shape[0]  #行数の取得
        X_scaled = np.array([])
        temp = np.array([])
        
        for j in range(raws):
            temp = np.append(temp, (X[j, 0] - self.mean_[0])/self.std_[0])
        X_scaled = temp.reshape(raws, 1)
        
        for i in range(1, cols):
            temp = np.array([])
            for k in range(raws):
                temp = np.append(temp, (X[k, i] - self.mean_[i])/self.std_[i])
            temp = temp.reshape(raws, 1)
            X_scaled = np.hstack((X_scaled, temp))

        
        pass
        return X_scaled

In [5]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]

scaler = StandardScaler()
scaler.fit(X)
print("平均 :", scaler.mean_)
print("分散 :", scaler.var_)
X_std = scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


In [10]:

print(X)
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
print("標準偏差 : {}".format(scratch_scaler.std_))
X_std = scratch_scaler.transform(X)
print(X_std)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
標準偏差 : [0.2764055  0.29137605 0.10246951 0.07483315]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


【問題4】 四則演算を行うクラスの作成
---

In [20]:
class FourOpeClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        try:
            val = int(value)
            self.value = val
            print("初期値{}が設定されました".format(self.value))
        
        except ValueError:
           print("That's not an int!")
            
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
    
    def sub(self, value2):
        """
        受け取った引数をself.valueから引く
        """
        self.value -= value2

    def multi(self, value2):
        """
        受け取った引数をself.valueとかける
        """
        self.value *= value2
   
    def div(self, value2):
        """
        self.valueを受け取った引数で割る
        """
        self.value /= value2
        
example = FourOpeClass(10.5)
print("value : {}".format(example.value))
example.div(5)
print("value : {}".format(example.value))

初期値10が設定されました
value : 10
value : 2.0
